apiVersion: apps/v1
kind: Deployment 
metadata:
  name: ews-registry-app
  labels:
    app: ews-registry-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ews-registry-app
  template:
    metadata:
      labels:
        app: ews-registry-app
    spec:
      containers:
      - name: ews-registry-app
        image: omprakashbhanarkar/ews-cicd:17
        ports:
        - containerPort: 8761     

   
