apiVersion: v1
kind: Service
metadata:
  name: ews-registry-app
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8761
    protocol: TCP
  selector:
    app: ews-registry-app
